name: Gatling Enterprise CI/CD

on:
  workflow_dispatch:   # ручной запуск
  push:
    branches:
      - main
  pull_request:

jobs:
  gatling:
    runs-on: ubuntu-latest

    steps:
      # Забираем код
      - uses: actions/checkout@v4

      # Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Сборка Maven
      - name: Build with Maven
        run: mvn clean compile

      # Запуск Gatling тестов
      - name: Run Gatling Tests
        run: ./run-all.sh

      # Сохраняем отчёты как артефакты
      - name: Archive Gatling Reports
        uses: actions/upload-artifact@v4
        with:
          name: gatling-reports
          path: target/gatling-reports/**git add .github/workflows/gatling-enterprise-workflow.yaml